import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import  { Toaster } from 'react-hot-toast';
import AuthContext from "@/context/AuthContext";

const inter = Inter({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      < AuthContext>
      <body
        className={inter.className}>
          <main className="mx-auto max-w-6xl  sm:px-6 lg:px-8">
            <Header/>
              {children}
              <Footer/>
              <Toaster/>
          </main>
      </body>
      </AuthContext>
    </html>
  );
}